### ISSUE TITLE
Support multiple selections

### ISSUE THREAD

**Issue by jkarsrud** [andersennl/case-switch#1]
Hi!

First of all, thanks for this package, it's already pretty essential to my workflow!
There is one minor thing that bugs me a bit though; it appears it doesn't support multiple selections. If I have multiple selections, it only case-switches the first one. It would be great if it supported multiple selections :smile:

**Comment by andersennl** [comment]
Hi @jkarsrud ,
thanks a lot, I'm really glad to head that you find this package useful! :)

Yes, the current state of the package was kind of a first version which I just started using myself and kind of forgot to develop any further :smile: I'll see if I can get it to work with multiple selections :+1:

**Comment by andersennl** [comment]
Hi again @jkarsrud 
I've just released a bigger update with more conversion commands and other things. I hope you find it useful.

I'm planning to release an update with support for multiple selections at the weekend :+1:

**Comment by jkarsrud** [comment]
Sweet, these changes look really good! Looking forward to multiple selections coming soon :+1:

**Comment by andersennl** [comment]
It will be ready in the next couple of days.

**Comment by andersennl** [comment]
@jkarsrud The update is finally ready :+1:. I hope it works as you expect.

**Comment by andersennl** [comment]
https://github.com/andersennl/case-switch/pull/2
