### ISSUE TITLE
Keybindings conflict with copy key

### ISSUE THREAD

**Issue by dabou** [andersennl/case-switch#5]
The keybindings 'ctrl-c ctrl-c' package are in conflict with native copy keybinding 'ctrl-c'. Half the time the copy don't work.
Can you enable  the personalization of keybindings in the package like the capture:
![capture du 2016-05-26 13 29 18](https://cloud.githubusercontent.com/assets/1374934/15573476/95acf926-2347-11e6-9c25-05011ccdb754.png)

Thereby the user can disable and change keybindings.

Thank's for your package.

**Comment by andersennl** [comment]
Hi @dabou thanks for bringing this to my attention.

I've looked into it - please correct me if I'm mistaken but I'm able to change the keybinding like this in your `keymap.cson`:
![bildschirmfoto 2016-05-26 um 17 03 45](https://cloud.githubusercontent.com/assets/2667916/15579199/e961afd2-2363-11e6-8bc3-b6ef759bbe3b.png)

You can additionally disable the preset keybindings:
![bildschirmfoto 2016-05-26 um 17 06 06](https://cloud.githubusercontent.com/assets/2667916/15579271/2e64d532-2364-11e6-8800-576b1ccdde31.png)

If you follow these steps, is there still a conflict? Or is the "disabling default keybindings" something you don't want to do?

**Comment by andersennl** [comment]
@dabou is there anything I can do for you? Otherwise I'd close the issue.

**Comment by dabou** [comment]
Thank's a lot !
When i add the keybinding in the user keymap file (`keymap.cson`), the preset keybindings appeared in the package settings and can disable.
So the conflict is resolved. :v: 

You can close the issue and thank you for your reactivity.

**Comment by andersennl** [comment]
Glad it works for you, I'll close the issue 👍

**Comment by steveoh** [comment]
I would suggest not using ctrl-c as a default. This breaks every windows user and is a pain to track down.

**Comment by andersennl** [comment]
@steveoh yes that's absolutely right. I can change it soon but feel free to create a pull request if you want to.
