### ISSUE TITLE
Seems Only "case-switch:convert-to-kebab-case" is working

### ISSUE THREAD

**Issue by ericfong** [andersennl/case-switch#7]
Try to set hot keys

```
'atom-workspace':
  "ctrl-alt-t": 'case-switch:toggle'
  "ctrl-alt-c": "case-switch:convert-to-camel-case"
  "ctrl-alt-s": "case-switch:convert-to-snake-case"
  "ctrl-alt-k": "case-switch:convert-to-kebab-case"
```

All work except ctrl-alt-k

Tried `alt-c ctrl-k`, also not working

Thanks for you help

**Comment by andersennl** [comment]
Hi @ericfong, does invoking the command via atom's command panel work for you?

**Comment by andersennl** [comment]
I'll close this issue. Feel free to open it up again if you have any questions.
